# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 163688f46c8a2567eee01c2ad50a01d227d77b8791f046e3c03983686b9a7971770dbbfe26abcdbd100a582ef670c4e9e158c6535cb66ce3e5f0016c44ffabd2

test:
  secret_key_base: 80e8523d62e5e28cedbe90eda0edeaaccd3aca3d4f30f6895698176c253fd3ae10f1f3f1686a1df1cc191ba4192c79f2b8cfa5b539fa81ff3bb6c9cbbf62c842

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
